version: '3'

services:

  # ==== Application ====

  app:
    container_name: EmperorGPT
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - TEST_GUILD_ID=$TEST_GUILD_ID
      - BOT_OWNER_ID=$BOT_OWNER_ID
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - API_PORT=$API_PORT
      - API_ADMIN_TOKEN=$API_ADMIN_TOKEN
      - WEBSOCKET_URL=ws://localhost:3001
      - IMGUR_CLIENT_ID=$IMGUR_CLIENT_ID
      - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - "4000:4000"
    volumes:
        - ./database:/app/database
        - ./logs/:/app/logs
        - ./assets:/app/assets
    restart: always
    # depends_on:
    #   - database

  # ==== MySQL database ====

  # database:
  #   image: mysql # or `mariadb`
  #   container_name: database
  #   restart: always
  #   volumes:
  #     - ./data:/var/lib/mysql:rw
  #   environment:
  #     - MYSQL_DATABASE=${DATABASE_NAME}
  #     - MYSQL_USER=${DATABASE_USER}
  #     - MYSQL_PASSWORD=${DATABASE_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - dev

  # ==== PostgreSQL database ====

  # database:
  #   image: postgres
  #   container_name: database
  #   restart: always
  #   volumes:
  #     - ./data:/var/lib/postgresql:rw
  #   environment:
  #     - POSTGRES_DB=${DATABASE_NAME}
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - dev

  # ==== phpMyAdmin ====

  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   depends_on:
  #       - database
  #   ports:
  #       - 8080:80
  #   environment:
  #       PMA_HOST: database
  #   networks:
  #       - dev
