name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-emperorgpt-image:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build EmperorGPT Image'
        run: |
          docker build -f .docker/app/Dockerfile . --tag ghcr.io/w33ts/emperorgpt:latest
          docker push ghcr.io/w33ts/emperorgpt:latest
